BAO-Driver: TestDriverAria5.c File Reference
TestDriverAria5.c File Reference
Functions
double DiffTime (struct timeval *heure_depart, struct timeval *heure_fin)
static void hdl (int sig, siginfo_t *info, void *unused)
void PrintDatas (unsigned long int *p)
void ReadDataByPolling ()
void ReadDataByInterrupt ()
void InitSpecs ()
void InitDmaTransfertByInterrupt ()
void InitDmaTransfertByPolling ()
void InitDmaTransfertToDevice ()
void InitDmaTransfertChipToChip ()
int main ()
Variables
int Card
unsigned int DmaSize = 0x100
unsigned char Mem [65536]
Function Documentation
double DiffTime (struct timeval * heure_depart, struct timeval * heure_fin)
Referenced by ReadDataByInterrupt(), and ReadDataByPolling().
static void hdl (int sig, siginfo_t * info, void * unused) [static]
Referenced by main().
void InitDmaTransfertByInterrupt ()
References Card, CHIP_MEM_BASE0, DmaSize, ENABLE, GET_STATE_END_DMA, LENGHT_ENDS_TRANSACTION, QUAD_WORD, SET_CONF_TRANSLATION_TABLE, and SOFT_RESET.
Referenced by main().
void InitDmaTransfertByPolling ()
References Card, CHIP_MEM_BASE0, DISABLE, DmaSize, GET_STATE_END_DMA, LENGHT_ENDS_TRANSACTION, QUAD_WORD, SET_CONF_TRANSLATION_TABLE, and SOFT_RESET.
Referenced by main().
void InitDmaTransfertChipToChip ()
References Card, CHIP_MEM_BASE0, DISABLE, DmaSize, GET_STATE_END_DMA, GO, LENGHT_ENDS_TRANSACTION, Mem, QUAD_WORD, SET_CONF_TRANSLATION_TABLE, SOFT_RESET, and SPECSM0_MEM.
Referenced by main().
void InitDmaTransfertToDevice ()
References Card, CHIP_MEM_BASE0, DISABLE, DmaSize, GET_STATE_END_DMA, GO, LENGHT_ENDS_TRANSACTION, Mem, QUAD_WORD, SET_CONF_TRANSLATION_TABLE, and SOFT_RESET.
Referenced by main().
void InitSpecs ()
References Card.
Referenced by main().
int main ()
References Card, GO, hdl(), InitDmaTransfertByInterrupt(), InitDmaTransfertByPolling(), InitDmaTransfertChipToChip(), InitDmaTransfertToDevice(), InitSpecs(), ReadDataByInterrupt(), ReadDataByPolling(), SIGTEST, and WRITE_IN_PIO_IN.
void PrintDatas (unsigned long int * p)
References DmaSize.
void ReadDataByInterrupt ()
References Card, DiffTime(), DISABLE, DmaSize, GO, and Mem.
Referenced by main().
void ReadDataByPolling ()
References Card, DiffTime(), DmaSize, GET_STATE_END_DMA, GO, and Mem.
Referenced by main().
Variable Documentation
int Card
Referenced by InitDmaTransfertByInterrupt(), InitDmaTransfertByPolling(), InitDmaTransfertChipToChip(), InitDmaTransfertToDevice(), InitSpecs(), main(), ReadDataByInterrupt(), and ReadDataByPolling().
unsigned int DmaSize = 0x100
Referenced by InitDmaTransfertByInterrupt(), InitDmaTransfertByPolling(), InitDmaTransfertChipToChip(), InitDmaTransfertToDevice(), PrintDatas(), ReadDataByInterrupt(), and ReadDataByPolling().
unsigned char Mem[65536]
Referenced by InitDmaTransfertChipToChip(), InitDmaTransfertToDevice(), ReadDataByInterrupt(), and ReadDataByPolling().