BAO-Driver: AltSpecsV2.c File Reference
AltSpecsV2.c File Reference
Data Structures
struct sgdma_register
struct AvalonMM_CSR
struct PIO_Register
struct FIFO_StatusRegister
struct Aria5Specs_dev
struct Master
Functions
MODULE_DEVICE_TABLE (pci, ids)
module_param (major, int, 0660)
MODULE_PARM_DESC (major,"Static major number (none = dynamic)")
static int specs_dev_init (struct Aria5Specs_dev *specs_dev)
static void specs_dev_exit (struct Aria5Specs_dev *specs_dev)
static irqreturn_t AltSpecsV2_isr (int irq, void *dev_id)
static int __devinit scan_bars (struct Aria5Specs_dev *specs_dev, struct pci_dev *dev)
static void unmap_bars (struct Aria5Specs_dev *specs_dev, struct pci_dev *dev)
static int __devinit map_bars (struct Aria5Specs_dev *specs_dev, struct pci_dev *dev)
static void __devinit test_version (struct Aria5Specs_dev *specs_dev)
static int __devinit probe (struct pci_dev *dev, const struct pci_device_id *id)
static void __devexit remove (struct pci_dev *dev)
static int specs_dev_open (struct inode *inode, struct file *file)
static int specs_dev_ioctl (struct inode *inode, struct file *file, unsigned int ioctl_num, unsigned long ioctl_param)
static ssize_t specs_dev_read (struct file *file, char __user *buf, size_t count, loff_t *pos)
static ssize_t specs_dev_write (struct file *file, const char __user *buf, size_t count, loff_t *pos)
static int specs_dev_close (struct inode *inode, struct file *file)
static int __init AltSpecsV2_init (void)
static void __exit AltSpecsV2_exit (void)
MODULE_LICENSE ("GPL")
module_init (AltSpecsV2_init)
module_exit (AltSpecsV2_exit)
Variables
struct task_struct * tsk
struct sgdma_register packed
static struct pci_device_id ids []
static int major = 0
static wait_queue_head_t pio_irq_waitq [NB_MASTER]
static int nb_irq [NB_MASTER] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
static int MaxDelay [NB_MASTER] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
static int SlaveIt [NB_MASTER] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
static struct Aria5Specs_dev * SpecsDev = NULL
static struct Master * MasterList [NB_MASTER] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
static struct file_operations specs_devfops
static struct pci_driver pci_driver
Function Documentation
static void __exit AltSpecsV2_exit (void) [static]
@ AltSpecsV2_init() - Module cleanup, unregisters devices.
References DRV_NAME.
static int __init AltSpecsV2_init (void) [static]
@ AltSpecsV2_init() - Module initialization, registers devices.
References DRV_NAME.
static irqreturn_t AltSpecsV2_isr (int irq, void * dev_id) [static]
Bug:
AltSpecsV2_isr() - Interrupt handler not working
References AVALON_DMA_CONTROLLER, Aria5Specs_dev::bar, BAR2, PIO_Register::data_status, DRV_NAME, PIO_Register::edge_capture, AvalonMM_CSR::interrupt_status, MASTERS_OFFSET, NB_MASTER, OFFSET_CROSSING_BRIDGE, PCI_EXPRESS_REGISTER, PIO_CTRL_REG, PIO_STATUS_REG, and Aria5Specs_dev::pioMasterStatusIrqs.
Referenced by probe().
static int __devinit map_bars (struct Aria5Specs_dev * specs_dev, struct pci_dev * dev) [static]
Map the device memory regions into kernel virtual address space after verifying their sizes respect the minimum sizes needed, given by the bar_min_len[] array.
Parameters:
specs_dev pointer of struct Aria5Specs_dev .
dev pointer of struct pci_dev
Return values:
rc status
< 0 Failure
0 = Success
References Aria5Specs_dev::bar, and DRV_NAME.
Referenced by probe().
MODULE_DEVICE_TABLE (pci , ids)
module_exit (AltSpecsV2_exit)
module_init (AltSpecsV2_init)
MODULE_LICENSE ("GPL")
module_param (major , int , 0660)
MODULE_PARM_DESC (major , "Static major number (none = dynamic)")
static int __devinit probe (struct pci_dev * dev, const struct pci_device_id * id) [static]
Called when the PCI sub system thinks we can control the given device. Inspect if we can support the device and if so take control of it.
Return 0 when we have taken control of the given device.
allocate board specific bookkeeping
allocate coherently-mapped memory for the descriptor table
enable the board
verify board revision
request regions
query DMA mask
obtain and request irq
map regions into kernel address space
Parameters:
dev struct pci_dev
id const struct pci_device_id
Returns:
0 is the device is reconized
Return values:
status The program status.
XXX check for native or legacy PCIe endpoint?
References AltSpecsV2_isr(), Aria5Specs_dev::bar, BAR2, DRV_NAME, PIO_Register::edge_capture, AvalonMM_CSR::enableIrq, Aria5Specs_dev::firstWriteFifo, Aria5Specs_dev::got_regions, Master::id, PIO_Register::interrupt_mask, AvalonMM_CSR::interrupt_status, Aria5Specs_dev::irq_count, Aria5Specs_dev::irq_num, map_bars(), Aria5Specs_dev::masterIdUsed, Aria5Specs_dev::minor, NB_MASTER, Aria5Specs_dev::pci_device, PCI_EXPRESS_REGISTER, PIO_MASTERS_FIFO_IRQS, PIO_MASTERS_STATUS_IRQS, Aria5Specs_dev::pioMasterFifoIrqs, Aria5Specs_dev::pioMasterStatusIrqs, Aria5Specs_dev::revision, scan_bars(), specs_dev_exit(), specs_dev_init(), test_version(), and unmap_bars().
static void __devexit remove (struct pci_dev * dev) [static]
Call when the driver is removed (call of rmmod) free the allocation of struct Aria5Specs_dev and the 16 struct Master
Parameters:
dev pointer of struct pci_dev
References DRV_NAME, Aria5Specs_dev::got_regions, Aria5Specs_dev::irq_num, NB_MASTER, Aria5Specs_dev::pci_device, specs_dev_exit(), and unmap_bars().
static int __devinit scan_bars (struct Aria5Specs_dev * specs_dev, struct pci_dev * dev) [static]
Find all the BAR used by the card and display it in the /var/log/messages or by dmesg
Parameters:
specs_dev pointer under struct Aria5Specs_dev
dev pointer under struct pci_dev
Return values:
always 0
References DRV_NAME.
Referenced by probe().
static int specs_dev_close (struct inode * inode, struct file * file) [static]
Called when the device goes from used to unused. called by close() in user programm
Parameters:
inode struct inode
file struct file
Return values:
0
References DRV_NAME, Aria5Specs_dev::masterIdUsed, and NB_MASTER.
static void specs_dev_exit (struct Aria5Specs_dev * specs_dev) [static]
specs_dev_exit() - Cleanup character device
XXX Should ideally be tied to the device, on device remove, not module exit.
References Aria5Specs_dev::cdev, Aria5Specs_dev::cdevno, and DRV_NAME.
Referenced by probe(), and remove().
static int specs_dev_init (struct Aria5Specs_dev * specs_dev) [static]
memory mapping of the virtuel memory for the user programm called by mmap(function not used)
Parameters:
file pointer of struct file
vma pointer of struct vm_area_struct
Return values:
0 if case of succes else < 0
specs_dev_init() - Initialize character device
Parameters:
specs_dev pointer of struct Aria5Specs_dev
Return values:
0 if succes else <0
References Aria5Specs_dev::cdev, Aria5Specs_dev::cdevno, Aria5Specs_dev::dma_lock, DRV_NAME, Aria5Specs_dev::minor, and Aria5Specs_dev::virtual_mem.
Referenced by probe().
static int specs_dev_ioctl (struct inode * inode, struct file * file, unsigned int ioctl_num, unsigned long ioctl_param) [static]
Management of all the functions of the Specs-v2 board
Parameters:
inode pointer of struct inode
file pointer of struct file
ioctl_num number of the command
ioctl_param argument if need by the command
Return values:
rc status
< 0 Failure
0 = Success
> 0
References _BUSIOPDATA::AccessType, _BUSIOPDATA::Address, ALMOST_EMPTY, FIFO_StatusRegister::almost_empty, ALMOST_FULL, FIFO_StatusRegister::almost_full, Aria5Specs_dev::bar, BAR2, BitSize32, _BUSIOPDATA::Buffer, _DEVICE_LOCATION::BusNumber, PIO_Register::data_status, PIO_Register::direction, DRV_NAME, PIO_Register::edge_capture, FIFO_StatusRegister::event, FIFO_EMISSION_OUT, FIFO_EMISSION_STATUS, FIFO_RECEPTION_IN, FIFO_RECEPTION_STATUS, Master::fifoEmiOut, Master::fifoEmiOut_Status, Master::fifoRecIn, Master::fifoRecIn_Status, FIFO_StatusRegister::fill_level, Aria5Specs_dev::firstWriteFifo, Master::id, FIFO_StatusRegister::interrupt_enable, PIO_Register::interrupt_mask, IOCTL_BUS_IOP_READ, IOCTL_BUS_IOP_WRITE, IOCTL_CHECK_SLAVE_IT, IOCTL_CLOSE_MASTER, IOCTL_DISABLE_PIO_INTERRUPT, IOCTL_ENABLE_PIO_INTERRUPT, IOCTL_FIFOS_INIT, IOCTL_FIND_DEVICE, IOCTL_OPEN_MASTER, IOCTL_READ_FILL_LEVEL, IOCTL_RESET, IT_FIFO, IT_STATUS, MASK_FIFO_IN, _BUSIOPDATA::MasterID, Aria5Specs_dev::masterIdUsed, MASTERS_OFFSET, NB_MASTER, OFFSET_CROSSING_BRIDGE, OFFSET_FIFO_REC_IN_STATUS, Aria5Specs_dev::pci_device, PIO_CTRL_REG, _INTERRUPT_OBJ::pio_line, PIO_STATUS_REG, Master::pioRegCtrl, Master::pioRegStatus, RESET, _DEVICE_LOCATION::SlotNumber, _INTERRUPT_OBJ::stat_reg, Aria5Specs_dev::test_version, and _BUSIOPDATA::TransferSize.
static int specs_dev_open (struct inode * inode, struct file * file) [static]
Called when the user application open on of device caracter /dev/AltSpecsV2[0-3]
Parameters:
inode pointer of struct inode
file pointer of struct file
Return values:
rc status
< 0 Failure
0 = Success
References DRV_NAME, Aria5Specs_dev::minor, and Aria5Specs_dev::test_version.
static ssize_t specs_dev_read (struct file * file, char __user * buf, size_t count, loff_t * pos) [static]
function not used in user program
Parameters:
file pointer of struct file
buf char pointer allocated by the user programm
count number of bytes to be copied in buf
pos offset in octets
Return values:
count number of bytes read (return to the user), if < 0 error
static ssize_t specs_dev_write (struct file * file, const char __user * buf, size_t count, loff_t * pos) [static]
not used by the user programm
Parameters:
file pointer of struct file
buf char pointer allocated by the user programm
count number of bytes to be copied in buf
pos offset in octets
Return values:
count number of bytes read from user space , < 0 if error.
static void __devinit test_version (struct Aria5Specs_dev * specs_dev) [static]
References Aria5Specs_dev::bar, BAR2, DRIVER_VERSION, DRV_NAME, Aria5Specs_dev::test_version, and VERSION.
Referenced by probe().
static void unmap_bars (struct Aria5Specs_dev * specs_dev, struct pci_dev * dev) [static]
Unmap the BAR regions that had been mapped earlier using map_bars()
Parameters:
specs_dev pointer of struct Aria5Specs_dev .
dev pointer of struct pci_dev
Returns:
nothing
References Aria5Specs_dev::bar.
Referenced by probe(), and remove().
Variable Documentation
struct pci_device_id ids[] [static]
Initial value:
  {
    { PCI_DEVICE( 0x1172, 0x0005) },
    {  }
  }
Using the subsystem vendor id and subsystem id, it is possible to distinguish between different cards bases around the same (third-party) logic core.
Default Altera vendor and device ID's, and some (non-reserved) ID's are now used here that are used amongst the testers/developers.
int major = 0 [static]
struct Master* MasterList[NB_MASTER] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0} [static]
int MaxDelay[NB_MASTER] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0} [static]
int nb_irq[NB_MASTER] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0} [static]
struct FIFO_StatusRegister packed
Descriptor Header, controls the DMA read engine or write engine. The SG-DMA controller core has three registers accessible from its Avalon-MM
DMA Descriptor See Table 23-9. DMA Descriptor Structure of chapiter 23. Scatter-Gather DMA Controller Core or Table 2-1: DMA Descriptor Field Description The SGDMA is not yet used SpecsV2 Translation table PCI-to-Avalon Address Translation
struct pci_driver pci_driver [static]
Initial value:
 {
  .name = DRV_NAME,
  .id_table = ids,
  .probe = probe,
  .remove = remove ,
}
wait_queue_head_t pio_irq_waitq[NB_MASTER] [static]
int SlaveIt[NB_MASTER] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0} [static]
struct file_operations specs_devfops [static]
Initial value:
 {
 .owner   = THIS_MODULE,
 .open    = specs_dev_open,
 .ioctl   = specs_dev_ioctl,
 .release = specs_dev_close,
 .read    = specs_dev_read,
 .write   = specs_dev_write,
}
struct Aria5Specs_dev* SpecsDev = NULL [static]
struct task_struct* tsk